# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sgFieldUI.ui'
#
# Created: Wed Apr 19 13:38:31 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1200, 600)
        self.verticalLayout_3 = QtGui.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter = QtGui.QSplitter(Form)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(8)
        self.splitter.setObjectName("splitter")
        self.verticalLayoutWidget = QtGui.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.EntitiesLbl = QtGui.QLabel(self.verticalLayoutWidget)
        self.EntitiesLbl.setStyleSheet("font: 75 12pt \"Arial\";")
        self.EntitiesLbl.setObjectName("EntitiesLbl")
        self.horizontalLayout_3.addWidget(self.EntitiesLbl)
        self.refreshPushButton = QtGui.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.refreshPushButton.sizePolicy().hasHeightForWidth())
        self.refreshPushButton.setSizePolicy(sizePolicy)
        self.refreshPushButton.setObjectName("refreshPushButton")
        self.horizontalLayout_3.addWidget(self.refreshPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.entityTable = QtGui.QTableWidget(self.verticalLayoutWidget)
        self.entityTable.setAlternatingRowColors(True)
        self.entityTable.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.entityTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.entityTable.setObjectName("entityTable")
        self.entityTable.setColumnCount(2)
        self.entityTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.entityTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.entityTable.setHorizontalHeaderItem(1, item)
        self.entityTable.horizontalHeader().setStretchLastSection(True)
        self.entityTable.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.entityTable)
        self.removeConnectionsCheckBox = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.removeConnectionsCheckBox.setChecked(True)
        self.removeConnectionsCheckBox.setObjectName("removeConnectionsCheckBox")
        self.verticalLayout.addWidget(self.removeConnectionsCheckBox)
        self.verticalLayoutWidget_5 = QtGui.QWidget(self.splitter)
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.label_2.setStyleSheet("font: 75 12pt \"Arial\";")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.fieldsTable = QtGui.QTableWidget(self.verticalLayoutWidget_5)
        self.fieldsTable.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.fieldsTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.fieldsTable.setObjectName("fieldsTable")
        self.fieldsTable.setColumnCount(2)
        self.fieldsTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.fieldsTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.fieldsTable.setHorizontalHeaderItem(1, item)
        self.fieldsTable.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_5.addWidget(self.fieldsTable)
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.splitter)
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label.setStyleSheet("font: 75 12pt \"Arial\";")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.FieldDataEdt = QtGui.QPlainTextEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.FieldDataEdt.setFont(font)
        self.FieldDataEdt.setObjectName("FieldDataEdt")
        self.verticalLayout_2.addWidget(self.FieldDataEdt)
        self.verticalLayout_3.addWidget(self.splitter)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.EntitiesLbl.setText(QtGui.QApplication.translate("Form", "Entities", None, QtGui.QApplication.UnicodeUTF8))
        self.refreshPushButton.setText(QtGui.QApplication.translate("Form", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.entityTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Form", "Entity Display Name", None, QtGui.QApplication.UnicodeUTF8))
        self.entityTable.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Form", "Entity Internal Name", None, QtGui.QApplication.UnicodeUTF8))
        self.removeConnectionsCheckBox.setText(QtGui.QApplication.translate("Form", "Remove Connection Entities from Results", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Fields", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldsTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Form", "Field Display Name", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldsTable.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Form", "Field  Internal Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Shotgun Schema", None, QtGui.QApplication.UnicodeUTF8))

